server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: storage
          uri: lb://storage
          predicates:
            - Path=/s/**
          filters:
            - StripPrefix=1
        - id: myroute
          uri: http://httpbin.org/
          predicates:
            - Path=/get
    discovery:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: debug
